# Generated by Django 4.2.3 on 2023-08-07 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
