# Generated by Django 4.2.3 on 2023-08-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ads", "0002_alter_ad_published_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="contact",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
