# Generated by Django 4.2.3 on 2023-08-08 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Ads", "0003_ad_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="published_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
