# Generated by Django 4.2.3 on 2023-08-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Ads", "0005_alter_ad_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="description",
            field=models.TextField(max_length=255),
        ),
    ]
